### Functions

In [39]:
import snap
import numpy as np
from numpy.linalg import norm


def get_matrix(graph):
    """ Making adjacency matrix from snap graph
    
    Arg:
        graph: snap graph
        
    Returns:
        adjacency matrix made from graph having 1/Nu as a weight of all edges
        where Nu is a number of outgoing edges from the node of index equal to row index
        (so Nu depends on row)
    """
    size = graph.GetNodes()
    matrix = np.zeros((size, size))

    for edge in graph.Edges():
        matrix[edge.GetSrcNId(), edge.GetDstNId()] = 1 / graph.GetNI(edge.GetSrcNId()).GetOutDeg()

    return matrix


def page_rank(a, d, eps, e="same"):
    """ Getting dominant eigenvector of d * a + (1-d) * e @ 1
    
    Args:
        a: adjacency matrix
        d: coefficient for random leap
        eps: value which is telling if difference between current and last eigenvector approximations
            are small enough to accept error
        e: probability of visiting node by random leap, "same" - all nodes has the same probability
            "weighed" - nodes with fewer incoming edges has higher probability
    
    Returns:
        dominant eigenvector of matrix d * a + (1-d) * e @ 1
    """
    size = a.shape[0]

    # every node has the same probability
    if e == "same":
        e = np.ones((size, 1)) / size
    # nodes which has fewer incoming edges has higher probability
    else:
        e = np.zeros((size, 1))
        e[:, 0] += np.sum(a, axis=0).T
        e /= norm(e, ord=1)

        e = 1 - e
        e /= norm(e, ord=1)

    r = e
    last_r = np.zeros(size)

    b = d * a + (1 - d) * e @ np.ones((1, size))

    while norm(r - last_r, ord=1) > eps:
        last_r = r.copy()
        r = b @ r

        d = norm(last_r, ord=1) - norm(r, ord=1)
        r += d * e

    return r

### Tests

In [40]:
# graph p2p-Gnutella08 from stanford website
graph_from_file = snap.LoadEdgeList(snap.PNGraph, "graph.txt")

# random graph generated by snap library
random_graph = snap.GenRndPowerLaw(20, 3)

matrix_file = get_matrix(graph_from_file)
matrix_random = get_matrix(random_graph)

#### d = 0.9

In [41]:
# e = "same", matrix from file
r = page_rank(matrix_file, 0.9, 10**(-8), e="same")
r

array([[2.83978890e-04],
       [9.67054791e-05],
       [9.67054791e-05],
       ...,
       [9.67054791e-05],
       [9.67054791e-05],
       [9.67054791e-05]])

In [42]:
# e = "weighed", matrix from file
r = page_rank(matrix_file, 0.9, 10**(-8), e="weighed")
r

array([[2.83816004e-04],
       [9.67425063e-05],
       [9.67228823e-05],
       ...,
       [9.67420702e-05],
       [9.67420702e-05],
       [9.67425063e-05]])

In [43]:
# e = "same", random matrix
r = page_rank(matrix_random, 0.9, 10**(-8), e="same")
r

array([[0.07548694],
       [0.0682165 ],
       [0.0682165 ],
       [0.05205996],
       [0.03590342],
       [0.0682165 ],
       [0.0682165 ],
       [0.0682165 ],
       [0.03590342],
       [0.0682165 ],
       [0.0682165 ],
       [0.03590342],
       [0.03590342],
       [0.03590342],
       [0.03590342],
       [0.03590342],
       [0.03590342],
       [0.03590342],
       [0.03590342],
       [0.03590342]])

In [44]:
# e = "weighed", random matrix
r = page_rank(matrix_random, 0.9, 10**(-8), e="weighed")
r

array([[0.07823122],
       [0.06888141],
       [0.07091398],
       [0.05239504],
       [0.03726371],
       [0.06888141],
       [0.06888141],
       [0.06888141],
       [0.03726371],
       [0.06888141],
       [0.06786513],
       [0.0338761 ],
       [0.0338761 ],
       [0.0338761 ],
       [0.03613451],
       [0.0338761 ],
       [0.03726371],
       [0.0338761 ],
       [0.0327469 ],
       [0.03613451]])

#### d = 0.85

In [45]:
# e = "same", matrix from file
r = page_rank(matrix_file, 0.85, 10**(-8), e="same")
r

array([[0.00027373],
       [0.00010058],
       [0.00010058],
       ...,
       [0.00010058],
       [0.00010058],
       [0.00010058]])

In [46]:
# e = "same", random matrix
r = page_rank(matrix_random, 0.85, 10**(-8), e="same")
r

array([[0.07409519],
       [0.06750439],
       [0.06750439],
       [0.05199662],
       [0.03648886],
       [0.06750439],
       [0.06750439],
       [0.06750439],
       [0.03648886],
       [0.06750439],
       [0.06750439],
       [0.03648886],
       [0.03648886],
       [0.03648886],
       [0.03648886],
       [0.03648886],
       [0.03648886],
       [0.03648886],
       [0.03648886],
       [0.03648886]])

#### d = 0.75

In [47]:
# e = "same", matrix from file
r = page_rank(matrix_file, 0.75, 10**(-8), e="same")
r

array([[0.00025498],
       [0.00010813],
       [0.00010813],
       ...,
       [0.00010813],
       [0.00010813],
       [0.00010813]])

In [48]:
# e = "same", random matrix
r = page_rank(matrix_random, 0.75, 10**(-8), e="same")
r

array([[0.0713023 ],
       [0.06599882],
       [0.06599882],
       [0.05185622],
       [0.03771361],
       [0.06599882],
       [0.06599882],
       [0.06599882],
       [0.03771361],
       [0.06599882],
       [0.06599882],
       [0.03771361],
       [0.03771361],
       [0.03771361],
       [0.03771361],
       [0.03771361],
       [0.03771361],
       [0.03771361],
       [0.03771361],
       [0.03771361]])

#### d = 0.6

In [49]:
# e = "same", matrix from file
r = page_rank(matrix_file, 0.6, 10**(-8), e="same")
r

array([[0.00023043],
       [0.00011902],
       [0.00011902],
       ...,
       [0.00011902],
       [0.00011902],
       [0.00011902]])

In [50]:
# e = "same", random matrix
r = page_rank(matrix_random, 0.6, 10**(-8), e="same")
r

array([[0.06709012],
       [0.06351727],
       [0.06351727],
       [0.05160778],
       [0.03969829],
       [0.06351727],
       [0.06351727],
       [0.06351727],
       [0.03969829],
       [0.06351727],
       [0.06351727],
       [0.03969829],
       [0.03969829],
       [0.03969829],
       [0.03969829],
       [0.03969829],
       [0.03969829],
       [0.03969829],
       [0.03969829],
       [0.03969829]])

#### d = 0.5

In [51]:
# e = "same", matrix from file
r = page_rank(matrix_file, 0.5, 10**(-8), e="same")
r

array([[0.00021597],
       [0.00012603],
       [0.00012603],
       ...,
       [0.00012603],
       [0.00012603],
       [0.00012603]])

In [52]:
# e = "same", random matrix
r = page_rank(matrix_random, 0.5, 10**(-8), e="same")
r

array([[0.06426735],
       [0.06169666],
       [0.06169666],
       [0.05141388],
       [0.04113111],
       [0.06169666],
       [0.06169666],
       [0.06169666],
       [0.04113111],
       [0.06169666],
       [0.06169666],
       [0.04113111],
       [0.04113111],
       [0.04113111],
       [0.04113111],
       [0.04113111],
       [0.04113111],
       [0.04113111],
       [0.04113111],
       [0.04113111]])